# Windows with MSVC 2015 (minimal requirement for rust MSVC compiler)
os: Visual Studio 2015

# Set environment variables
environment:
  # For all jobs
  global:
    # Show rust backtrace on error
    RUST_BACKTRACE: 1
  # For every job
  matrix:
    # MSVC toolchain
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
    # GNU toolchain
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu

# Configure jobs
matrix:
  # Ignore failures in jobs with nightly channel
  allow_failures:
    - channel: nightly

# Install software
install:
  # Load rust installer
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  # Install rust toolchain
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  # Add global access to rust binaries
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  # Show rust version (detailed)
  - rustc -Vv
  - cargo -Vv

# Disable warning of missing MSVC project files in build directory
build: false

# Run rust build by scripting (in later test stage)
test_script:
  - cargo build -p ssb_parser --verbose
  - cargo test -p ssb_parser --verbose