# See <https://docs.travis-ci.com/user/job-lifecycle/>

# Ubuntu (xenial) as operating system
dist: xenial
# Rust as project language
language: rust
# Just for 'master' branch
branches:
  only:
    - master

# Add environment variable to show rust backtrace on error
env:
  global:
    - RUST_BACKTRACE=1
# Cache build dependencies
cache: cargo

# Jobs configuration
matrix:
  # Ignore failures in nightly release
  allow_failures:
    - rust: nightly
  # Don't wait for allowed failures to report final status
  fast_finish: true
  # Define jobs
  include:
    # Stable
    - rust: stable
      # CodeCov upload <https://github.com/SimonKagstrom/kcov>
      after_success: |
        sudo apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev && # Install kcov requirements
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && # Download kcov sources
        tar xzf master.tar.gz && cd kcov-master &&  # Unzip kcov sources
        mkdir build && cd build &&  # Make intermediate kcov build directory
        cmake .. && make && # Generate Makefile by CMake and build kcov
        sudo make install &&  # Install kcov to system
        cd ../.. && rm -rf kcov-master && # Delete kcov sources
        for file in target/debug/*_*-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&  # Generate code coverage reports
        bash <(curl -s https://codecov.io/bash) # Upload code coverage reports (by environment variable CODECOV_TOKEN)
      # Crates.io release
      deploy:
        provider: script  # Script execution
        script: cargo login $CRATES_TOKEN; cargo publish --manifest-path ssb_parser/Cargo.toml || true; cargo publish --manifest-path ssb_renderer/Cargo.toml || true; cargo publish --manifest-path ssb_filter/Cargo.toml || true  # Link to crates.io and publish ssb_* projects
        on:
          tags: true  # Commit must be tagged!
    # Nightly
    - rust: nightly

# Preparations for compilation
before_script:
  # Install vapoursynth
  - sudo bash ssb_filter/deps/vapoursynth-install.sh
  # Add test fonts (from windows)
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install -y ttf-mscorefonts-installer

# Execute rust builds & tests
script:
  - cargo build --verbose
  - cargo test --verbose